api:
  port: :8080
database:
  host: localhost
  port: 3306
  user: root
  password: secret
  name: smsgateway
rabbitmq:
  url: amqp://guest:guest@localhost:5672/
provider:
  timeout: 2s
  max_retry: 1
  enable: true
  url: ""